title: Jisu Jeun
author: Jisu Jeun
email: jeun@wiwi.uni-frankfurt.de
description: > # this means to ignore newlines until "show_exerpts:"
  Welcome! I'm a PhD Candidate at Goethe University Frankfurt.
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: /texture

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Adam Denisov
  tagline: Developer. Designer
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: true

  # generate social links in footer
  social_links:
    twitter: thelehhman
    github:  thelehhman
    linkedIn: in/thelehhman
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
